/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AegisVault {
  export type ProtectionActionStruct = {
    agentId: BigNumberish;
    user: AddressLike;
    actionType: BigNumberish;
    value: BigNumberish;
    timestamp: BigNumberish;
    reasonHash: BytesLike;
    successful: boolean;
  };

  export type ProtectionActionStructOutput = [
    agentId: bigint,
    user: string,
    actionType: bigint,
    value: bigint,
    timestamp: bigint,
    reasonHash: string,
    successful: boolean
  ] & {
    agentId: bigint;
    user: string;
    actionType: bigint;
    value: bigint;
    timestamp: bigint;
    reasonHash: string;
    successful: boolean;
  };

  export type RiskProfileStruct = {
    maxSlippage: BigNumberish;
    stopLossThreshold: BigNumberish;
    maxSingleActionValue: BigNumberish;
    allowAutoWithdraw: boolean;
    allowAutoSwap: boolean;
  };

  export type RiskProfileStructOutput = [
    maxSlippage: bigint,
    stopLossThreshold: bigint,
    maxSingleActionValue: bigint,
    allowAutoWithdraw: boolean,
    allowAutoSwap: boolean
  ] & {
    maxSlippage: bigint;
    stopLossThreshold: bigint;
    maxSingleActionValue: bigint;
    allowAutoWithdraw: boolean;
    allowAutoSwap: boolean;
  };

  export type PositionStruct = {
    ethBalance: BigNumberish;
    depositTimestamp: BigNumberish;
    lastActionTimestamp: BigNumberish;
    isActive: boolean;
    authorizedAgentId: BigNumberish;
    agentAuthorized: boolean;
    riskProfile: AegisVault.RiskProfileStruct;
  };

  export type PositionStructOutput = [
    ethBalance: bigint,
    depositTimestamp: bigint,
    lastActionTimestamp: bigint,
    isActive: boolean,
    authorizedAgentId: bigint,
    agentAuthorized: boolean,
    riskProfile: AegisVault.RiskProfileStructOutput
  ] & {
    ethBalance: bigint;
    depositTimestamp: bigint;
    lastActionTimestamp: bigint;
    isActive: boolean;
    authorizedAgentId: bigint;
    agentAuthorized: boolean;
    riskProfile: AegisVault.RiskProfileStructOutput;
  };
}

export interface AegisVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "actionHistory"
      | "agentActions"
      | "authorizeAgent"
      | "authorizedOperators"
      | "deposit"
      | "depositToken"
      | "depositsPaused"
      | "emergencyWithdraw"
      | "executeProtection"
      | "getAction"
      | "getActionCount"
      | "getAgentActions"
      | "getPosition"
      | "getRiskProfile"
      | "getTokenBalance"
      | "getUserActions"
      | "getUserDepositETH"
      | "getUserTokens"
      | "getVaultStats"
      | "minDeposit"
      | "owner"
      | "positions"
      | "protocolFeeBps"
      | "registryAddress"
      | "renounceOwnership"
      | "revokeAgent"
      | "setDepositsPaused"
      | "setMinDeposit"
      | "setOperatorAuthorization"
      | "setProtocolFee"
      | "tokenBalances"
      | "totalActionsExecuted"
      | "totalEthDeposited"
      | "totalValueProtected"
      | "transferOwnership"
      | "updateRiskProfile"
      | "userActions"
      | "userTokens"
      | "withdraw"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAuthorized"
      | "AgentRevoked"
      | "Deposited"
      | "ETHDeposited"
      | "EmergencyWithdrawal"
      | "OwnershipTransferred"
      | "ProtectionExecuted"
      | "RiskProfileUpdated"
      | "TokenDeposited"
      | "TokenWithdrawn"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "actionHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentActions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositsPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeProtection",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentActions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserActions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDepositETH",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositsPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperatorAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBalances",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalActionsExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEthDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalValueProtected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskProfile",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "userActions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "actionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDepositETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperatorAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalActionsExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEthDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValueProtected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace AgentAuthorizedEvent {
  export type InputTuple = [user: AddressLike, agentId: BigNumberish];
  export type OutputTuple = [user: string, agentId: bigint];
  export interface OutputObject {
    user: string;
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRevokedEvent {
  export type InputTuple = [user: AddressLike, agentId: BigNumberish];
  export type OutputTuple = [user: string, agentId: bigint];
  export interface OutputObject {
    user: string;
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ETHDepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalEvent {
  export type InputTuple = [user: AddressLike, ethAmount: BigNumberish];
  export type OutputTuple = [user: string, ethAmount: bigint];
  export interface OutputObject {
    user: string;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtectionExecutedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    agentId: BigNumberish,
    user: AddressLike,
    actionType: BigNumberish,
    value: BigNumberish,
    reasonHash: BytesLike,
    successful: boolean
  ];
  export type OutputTuple = [
    actionId: bigint,
    agentId: bigint,
    user: string,
    actionType: bigint,
    value: bigint,
    reasonHash: string,
    successful: boolean
  ];
  export interface OutputObject {
    actionId: bigint;
    agentId: bigint;
    user: string;
    actionType: bigint;
    value: bigint;
    reasonHash: string;
    successful: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskProfileUpdatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AegisVault extends BaseContract {
  connect(runner?: ContractRunner | null): AegisVault;
  waitForDeployment(): Promise<this>;

  interface: AegisVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  actionHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, string, boolean] & {
        agentId: bigint;
        user: string;
        actionType: bigint;
        value: bigint;
        timestamp: bigint;
        reasonHash: string;
        successful: boolean;
      }
    ],
    "view"
  >;

  agentActions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  authorizeAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  depositToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositsPaused: TypedContractMethod<[], [boolean], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  executeProtection: TypedContractMethod<
    [
      user: AddressLike,
      actionType: BigNumberish,
      value: BigNumberish,
      reasonHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getAction: TypedContractMethod<
    [actionId: BigNumberish],
    [AegisVault.ProtectionActionStructOutput],
    "view"
  >;

  getActionCount: TypedContractMethod<[], [bigint], "view">;

  getAgentActions: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getPosition: TypedContractMethod<
    [user: AddressLike],
    [AegisVault.PositionStructOutput],
    "view"
  >;

  getRiskProfile: TypedContractMethod<
    [user: AddressLike],
    [AegisVault.RiskProfileStructOutput],
    "view"
  >;

  getTokenBalance: TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getUserActions: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getUserDepositETH: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserTokens: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getVaultStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalEthDeposited: bigint;
        _totalActionsExecuted: bigint;
        _totalValueProtected: bigint;
      }
    ],
    "view"
  >;

  minDeposit: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        AegisVault.RiskProfileStructOutput
      ] & {
        ethBalance: bigint;
        depositTimestamp: bigint;
        lastActionTimestamp: bigint;
        isActive: boolean;
        authorizedAgentId: bigint;
        agentAuthorized: boolean;
        riskProfile: AegisVault.RiskProfileStructOutput;
      }
    ],
    "view"
  >;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  registryAddress: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeAgent: TypedContractMethod<[], [void], "nonpayable">;

  setDepositsPaused: TypedContractMethod<
    [paused: boolean],
    [void],
    "nonpayable"
  >;

  setMinDeposit: TypedContractMethod<
    [newMinDeposit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOperatorAuthorization: TypedContractMethod<
    [operator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setProtocolFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenBalances: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  totalActionsExecuted: TypedContractMethod<[], [bigint], "view">;

  totalEthDeposited: TypedContractMethod<[], [bigint], "view">;

  totalValueProtected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRiskProfile: TypedContractMethod<
    [
      maxSlippage: BigNumberish,
      stopLossThreshold: BigNumberish,
      maxSingleActionValue: BigNumberish,
      allowAutoWithdraw: boolean,
      allowAutoSwap: boolean
    ],
    [void],
    "nonpayable"
  >;

  userActions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userTokens: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "actionHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, string, boolean] & {
        agentId: bigint;
        user: string;
        actionType: bigint;
        value: bigint;
        timestamp: bigint;
        reasonHash: string;
        successful: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agentActions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositsPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeProtection"
  ): TypedContractMethod<
    [
      user: AddressLike,
      actionType: BigNumberish,
      value: BigNumberish,
      reasonHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAction"
  ): TypedContractMethod<
    [actionId: BigNumberish],
    [AegisVault.ProtectionActionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentActions"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [user: AddressLike],
    [AegisVault.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRiskProfile"
  ): TypedContractMethod<
    [user: AddressLike],
    [AegisVault.RiskProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenBalance"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserActions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserDepositETH"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTokens"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVaultStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalEthDeposited: bigint;
        _totalActionsExecuted: bigint;
        _totalValueProtected: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "minDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        AegisVault.RiskProfileStructOutput
      ] & {
        ethBalance: bigint;
        depositTimestamp: bigint;
        lastActionTimestamp: bigint;
        isActive: boolean;
        authorizedAgentId: bigint;
        agentAuthorized: boolean;
        riskProfile: AegisVault.RiskProfileStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAgent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositsPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinDeposit"
  ): TypedContractMethod<[newMinDeposit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperatorAuthorization"
  ): TypedContractMethod<
    [operator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProtocolFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenBalances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalActionsExecuted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalEthDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalValueProtected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRiskProfile"
  ): TypedContractMethod<
    [
      maxSlippage: BigNumberish,
      stopLossThreshold: BigNumberish,
      maxSingleActionValue: BigNumberish,
      allowAutoWithdraw: boolean,
      allowAutoSwap: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userActions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTokens"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentAuthorized"
  ): TypedContractEvent<
    AgentAuthorizedEvent.InputTuple,
    AgentAuthorizedEvent.OutputTuple,
    AgentAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRevoked"
  ): TypedContractEvent<
    AgentRevokedEvent.InputTuple,
    AgentRevokedEvent.OutputTuple,
    AgentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "ETHDeposited"
  ): TypedContractEvent<
    ETHDepositedEvent.InputTuple,
    ETHDepositedEvent.OutputTuple,
    ETHDepositedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawal"
  ): TypedContractEvent<
    EmergencyWithdrawalEvent.InputTuple,
    EmergencyWithdrawalEvent.OutputTuple,
    EmergencyWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProtectionExecuted"
  ): TypedContractEvent<
    ProtectionExecutedEvent.InputTuple,
    ProtectionExecutedEvent.OutputTuple,
    ProtectionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RiskProfileUpdated"
  ): TypedContractEvent<
    RiskProfileUpdatedEvent.InputTuple,
    RiskProfileUpdatedEvent.OutputTuple,
    RiskProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDeposited"
  ): TypedContractEvent<
    TokenDepositedEvent.InputTuple,
    TokenDepositedEvent.OutputTuple,
    TokenDepositedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWithdrawn"
  ): TypedContractEvent<
    TokenWithdrawnEvent.InputTuple,
    TokenWithdrawnEvent.OutputTuple,
    TokenWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentAuthorized(address,uint256)": TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;
    AgentAuthorized: TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;

    "AgentRevoked(address,uint256)": TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;
    AgentRevoked: TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "ETHDeposited(address,uint256)": TypedContractEvent<
      ETHDepositedEvent.InputTuple,
      ETHDepositedEvent.OutputTuple,
      ETHDepositedEvent.OutputObject
    >;
    ETHDeposited: TypedContractEvent<
      ETHDepositedEvent.InputTuple,
      ETHDepositedEvent.OutputTuple,
      ETHDepositedEvent.OutputObject
    >;

    "EmergencyWithdrawal(address,uint256)": TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;
    EmergencyWithdrawal: TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProtectionExecuted(uint256,uint256,address,uint8,uint256,bytes32,bool)": TypedContractEvent<
      ProtectionExecutedEvent.InputTuple,
      ProtectionExecutedEvent.OutputTuple,
      ProtectionExecutedEvent.OutputObject
    >;
    ProtectionExecuted: TypedContractEvent<
      ProtectionExecutedEvent.InputTuple,
      ProtectionExecutedEvent.OutputTuple,
      ProtectionExecutedEvent.OutputObject
    >;

    "RiskProfileUpdated(address)": TypedContractEvent<
      RiskProfileUpdatedEvent.InputTuple,
      RiskProfileUpdatedEvent.OutputTuple,
      RiskProfileUpdatedEvent.OutputObject
    >;
    RiskProfileUpdated: TypedContractEvent<
      RiskProfileUpdatedEvent.InputTuple,
      RiskProfileUpdatedEvent.OutputTuple,
      RiskProfileUpdatedEvent.OutputObject
    >;

    "TokenDeposited(address,address,uint256)": TypedContractEvent<
      TokenDepositedEvent.InputTuple,
      TokenDepositedEvent.OutputTuple,
      TokenDepositedEvent.OutputObject
    >;
    TokenDeposited: TypedContractEvent<
      TokenDepositedEvent.InputTuple,
      TokenDepositedEvent.OutputTuple,
      TokenDepositedEvent.OutputObject
    >;

    "TokenWithdrawn(address,address,uint256)": TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;
    TokenWithdrawn: TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
