/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AegisRegistry {
  export type AgentInfoStruct = {
    name: string;
    agentURI: string;
    operator: AddressLike;
    registeredAt: BigNumberish;
    totalDecisions: BigNumberish;
    successfulActions: BigNumberish;
    totalValueProtected: BigNumberish;
    status: BigNumberish;
    tier: BigNumberish;
  };

  export type AgentInfoStructOutput = [
    name: string,
    agentURI: string,
    operator: string,
    registeredAt: bigint,
    totalDecisions: bigint,
    successfulActions: bigint,
    totalValueProtected: bigint,
    status: bigint,
    tier: bigint
  ] & {
    name: string;
    agentURI: string;
    operator: string;
    registeredAt: bigint;
    totalDecisions: bigint;
    successfulActions: bigint;
    totalValueProtected: bigint;
    status: bigint;
    tier: bigint;
  };
}

export interface AegisRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "approve"
      | "authorizedVaults"
      | "balanceOf"
      | "getAgent"
      | "getAgentCount"
      | "getApproved"
      | "getReputationCount"
      | "getReputationScore"
      | "getSuccessRate"
      | "giveFeedback"
      | "hasAgent"
      | "isAgentActive"
      | "isApprovedForAll"
      | "maxAgents"
      | "name"
      | "operatorToAgent"
      | "owner"
      | "ownerOf"
      | "recordAgentAction"
      | "registerAgent"
      | "registrationFee"
      | "renounceOwnership"
      | "reputationLog"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setAgentStatus"
      | "setApprovalForAll"
      | "setRegistrationFee"
      | "setVaultAuthorization"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
      | "updateAgentURI"
      | "upgradeAgentTier"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentMetadataUpdated"
      | "AgentRegistered"
      | "AgentStatsUpdated"
      | "AgentStatusChanged"
      | "AgentTierUpgraded"
      | "Approval"
      | "ApprovalForAll"
      | "OwnershipTransferred"
      | "ReputationFeedback"
      | "Transfer"
      | "VaultAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSuccessRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveFeedback",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "maxAgents", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "operatorToAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAgentAction",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registrationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationLog",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgentURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeAgentTier",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSuccessRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "giveFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAgentActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxAgents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operatorToAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAgentAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAgentTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace AgentMetadataUpdatedEvent {
  export type InputTuple = [agentId: BigNumberish, newURI: string];
  export type OutputTuple = [agentId: bigint, newURI: string];
  export interface OutputObject {
    agentId: bigint;
    newURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    operator: AddressLike,
    name: string,
    tier: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    operator: string,
    name: string,
    tier: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    operator: string;
    name: string;
    tier: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatsUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    totalDecisions: BigNumberish,
    successfulActions: BigNumberish,
    totalValueProtected: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    totalDecisions: bigint,
    successfulActions: bigint,
    totalValueProtected: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    totalDecisions: bigint;
    successfulActions: bigint;
    totalValueProtected: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusChangedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentTierUpgradedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    oldTier: BigNumberish,
    newTier: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, oldTier: bigint, newTier: bigint];
  export interface OutputObject {
    agentId: bigint;
    oldTier: bigint;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationFeedbackEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    reviewer: AddressLike,
    score: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    reviewer: string,
    score: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    reviewer: string;
    score: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultAuthorizedEvent {
  export type InputTuple = [vault: AddressLike, authorized: boolean];
  export type OutputTuple = [vault: string, authorized: boolean];
  export interface OutputObject {
    vault: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AegisRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AegisRegistry;
  waitForDeployment(): Promise<this>;

  interface: AegisRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        name: string;
        agentURI: string;
        operator: string;
        registeredAt: bigint;
        totalDecisions: bigint;
        successfulActions: bigint;
        totalValueProtected: bigint;
        status: bigint;
        tier: bigint;
      }
    ],
    "view"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedVaults: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  getAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [AegisRegistry.AgentInfoStructOutput],
    "view"
  >;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getReputationCount: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  getReputationScore: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  getSuccessRate: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  giveFeedback: TypedContractMethod<
    [agentId: BigNumberish, score: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;

  hasAgent: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isAgentActive: TypedContractMethod<
    [agentId: BigNumberish],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  maxAgents: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  operatorToAgent: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  recordAgentAction: TypedContractMethod<
    [
      agentId: BigNumberish,
      wasSuccessful: boolean,
      valueProtected: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [name: string, agentURI: string, tier: BigNumberish],
    [bigint],
    "payable"
  >;

  registrationFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationLog: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        reviewer: string;
        score: bigint;
        comment: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setAgentStatus: TypedContractMethod<
    [agentId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setRegistrationFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVaultAuthorization: TypedContractMethod<
    [vault: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgentURI: TypedContractMethod<
    [agentId: BigNumberish, newURI: string],
    [void],
    "nonpayable"
  >;

  upgradeAgentTier: TypedContractMethod<
    [agentId: BigNumberish, newTier: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        name: string;
        agentURI: string;
        operator: string;
        registeredAt: bigint;
        totalDecisions: bigint;
        successfulActions: bigint;
        totalValueProtected: bigint;
        status: bigint;
        tier: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedVaults"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [AegisRegistry.AgentInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getReputationCount"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputationScore"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSuccessRate"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "giveFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish, score: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAgent"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAgentActive"
  ): TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operatorToAgent"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "recordAgentAction"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      wasSuccessful: boolean,
      valueProtected: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, agentURI: string, tier: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registrationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationLog"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        reviewer: string;
        score: bigint;
        comment: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentStatus"
  ): TypedContractMethod<
    [agentId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRegistrationFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultAuthorization"
  ): TypedContractMethod<
    [vault: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgentURI"
  ): TypedContractMethod<
    [agentId: BigNumberish, newURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeAgentTier"
  ): TypedContractMethod<
    [agentId: BigNumberish, newTier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentMetadataUpdated"
  ): TypedContractEvent<
    AgentMetadataUpdatedEvent.InputTuple,
    AgentMetadataUpdatedEvent.OutputTuple,
    AgentMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatsUpdated"
  ): TypedContractEvent<
    AgentStatsUpdatedEvent.InputTuple,
    AgentStatsUpdatedEvent.OutputTuple,
    AgentStatsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusChanged"
  ): TypedContractEvent<
    AgentStatusChangedEvent.InputTuple,
    AgentStatusChangedEvent.OutputTuple,
    AgentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "AgentTierUpgraded"
  ): TypedContractEvent<
    AgentTierUpgradedEvent.InputTuple,
    AgentTierUpgradedEvent.OutputTuple,
    AgentTierUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationFeedback"
  ): TypedContractEvent<
    ReputationFeedbackEvent.InputTuple,
    ReputationFeedbackEvent.OutputTuple,
    ReputationFeedbackEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "VaultAuthorized"
  ): TypedContractEvent<
    VaultAuthorizedEvent.InputTuple,
    VaultAuthorizedEvent.OutputTuple,
    VaultAuthorizedEvent.OutputObject
  >;

  filters: {
    "AgentMetadataUpdated(uint256,string)": TypedContractEvent<
      AgentMetadataUpdatedEvent.InputTuple,
      AgentMetadataUpdatedEvent.OutputTuple,
      AgentMetadataUpdatedEvent.OutputObject
    >;
    AgentMetadataUpdated: TypedContractEvent<
      AgentMetadataUpdatedEvent.InputTuple,
      AgentMetadataUpdatedEvent.OutputTuple,
      AgentMetadataUpdatedEvent.OutputObject
    >;

    "AgentRegistered(uint256,address,string,uint8,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatsUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      AgentStatsUpdatedEvent.InputTuple,
      AgentStatsUpdatedEvent.OutputTuple,
      AgentStatsUpdatedEvent.OutputObject
    >;
    AgentStatsUpdated: TypedContractEvent<
      AgentStatsUpdatedEvent.InputTuple,
      AgentStatsUpdatedEvent.OutputTuple,
      AgentStatsUpdatedEvent.OutputObject
    >;

    "AgentStatusChanged(uint256,uint8,uint8)": TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;
    AgentStatusChanged: TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;

    "AgentTierUpgraded(uint256,uint8,uint8)": TypedContractEvent<
      AgentTierUpgradedEvent.InputTuple,
      AgentTierUpgradedEvent.OutputTuple,
      AgentTierUpgradedEvent.OutputObject
    >;
    AgentTierUpgraded: TypedContractEvent<
      AgentTierUpgradedEvent.InputTuple,
      AgentTierUpgradedEvent.OutputTuple,
      AgentTierUpgradedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationFeedback(uint256,address,uint8,uint256)": TypedContractEvent<
      ReputationFeedbackEvent.InputTuple,
      ReputationFeedbackEvent.OutputTuple,
      ReputationFeedbackEvent.OutputObject
    >;
    ReputationFeedback: TypedContractEvent<
      ReputationFeedbackEvent.InputTuple,
      ReputationFeedbackEvent.OutputTuple,
      ReputationFeedbackEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "VaultAuthorized(address,bool)": TypedContractEvent<
      VaultAuthorizedEvent.InputTuple,
      VaultAuthorizedEvent.OutputTuple,
      VaultAuthorizedEvent.OutputObject
    >;
    VaultAuthorized: TypedContractEvent<
      VaultAuthorizedEvent.InputTuple,
      VaultAuthorizedEvent.OutputTuple,
      VaultAuthorizedEvent.OutputObject
    >;
  };
}
