/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DecisionLogger {
  export type DecisionStruct = {
    agentId: BigNumberish;
    targetUser: AddressLike;
    decisionType: BigNumberish;
    riskLevel: BigNumberish;
    confidence: BigNumberish;
    analysisHash: BytesLike;
    dataHash: BytesLike;
    timestamp: BigNumberish;
    actionTaken: boolean;
    actionId: BigNumberish;
  };

  export type DecisionStructOutput = [
    agentId: bigint,
    targetUser: string,
    decisionType: bigint,
    riskLevel: bigint,
    confidence: bigint,
    analysisHash: string,
    dataHash: string,
    timestamp: bigint,
    actionTaken: boolean,
    actionId: bigint
  ] & {
    agentId: bigint;
    targetUser: string;
    decisionType: bigint;
    riskLevel: bigint;
    confidence: bigint;
    analysisHash: string;
    dataHash: string;
    timestamp: bigint;
    actionTaken: boolean;
    actionId: bigint;
  };

  export type RiskSnapshotStruct = {
    timestamp: BigNumberish;
    overallRisk: BigNumberish;
    liquidationRisk: BigNumberish;
    volatilityScore: BigNumberish;
    protocolRisk: BigNumberish;
    smartContractRisk: BigNumberish;
    detailsHash: BytesLike;
  };

  export type RiskSnapshotStructOutput = [
    timestamp: bigint,
    overallRisk: bigint,
    liquidationRisk: bigint,
    volatilityScore: bigint,
    protocolRisk: bigint,
    smartContractRisk: bigint,
    detailsHash: string
  ] & {
    timestamp: bigint;
    overallRisk: bigint;
    liquidationRisk: bigint;
    volatilityScore: bigint;
    protocolRisk: bigint;
    smartContractRisk: bigint;
    detailsHash: string;
  };
}

export interface DecisionLoggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentDecisions"
      | "authorizedLoggers"
      | "decisions"
      | "getAgentDecisions"
      | "getDecision"
      | "getDecisionCount"
      | "getLatestRisk"
      | "getRecentDecisions"
      | "getRiskHistory"
      | "getRiskHistoryCount"
      | "getStats"
      | "getUserDecisions"
      | "latestRiskSnapshot"
      | "logDecision"
      | "owner"
      | "renounceOwnership"
      | "riskHistory"
      | "setLoggerAuthorization"
      | "totalProtectionsTriggered"
      | "totalThreatsDetected"
      | "transferOwnership"
      | "updateRiskSnapshot"
      | "userDecisions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecisionLogged"
      | "LoggerAuthorized"
      | "OwnershipTransferred"
      | "RiskSnapshotUpdated"
      | "ThreatDetected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentDecisions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedLoggers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentDecisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecision",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecisionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestRisk",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentDecisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskHistoryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUserDecisions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRiskSnapshot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logDecision",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLoggerAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalProtectionsTriggered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalThreatsDetected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskSnapshot",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userDecisions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentDecisions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedLoggers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decisions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentDecisions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecisionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentDecisions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserDecisions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRiskSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLoggerAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProtectionsTriggered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalThreatsDetected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDecisions",
    data: BytesLike
  ): Result;
}

export namespace DecisionLoggedEvent {
  export type InputTuple = [
    decisionId: BigNumberish,
    agentId: BigNumberish,
    targetUser: AddressLike,
    decisionType: BigNumberish,
    riskLevel: BigNumberish,
    confidence: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    decisionId: bigint,
    agentId: bigint,
    targetUser: string,
    decisionType: bigint,
    riskLevel: bigint,
    confidence: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    decisionId: bigint;
    agentId: bigint;
    targetUser: string;
    decisionType: bigint;
    riskLevel: bigint;
    confidence: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoggerAuthorizedEvent {
  export type InputTuple = [logger: AddressLike, authorized: boolean];
  export type OutputTuple = [logger: string, authorized: boolean];
  export interface OutputObject {
    logger: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskSnapshotUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    overallRisk: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    overallRisk: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    overallRisk: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThreatDetectedEvent {
  export type InputTuple = [
    decisionId: BigNumberish,
    agentId: BigNumberish,
    targetUser: AddressLike,
    severity: BigNumberish,
    analysisHash: BytesLike
  ];
  export type OutputTuple = [
    decisionId: bigint,
    agentId: bigint,
    targetUser: string,
    severity: bigint,
    analysisHash: string
  ];
  export interface OutputObject {
    decisionId: bigint;
    agentId: bigint;
    targetUser: string;
    severity: bigint;
    analysisHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DecisionLogger extends BaseContract {
  connect(runner?: ContractRunner | null): DecisionLogger;
  waitForDeployment(): Promise<this>;

  interface: DecisionLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentDecisions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  authorizedLoggers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  decisions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        agentId: bigint;
        targetUser: string;
        decisionType: bigint;
        riskLevel: bigint;
        confidence: bigint;
        analysisHash: string;
        dataHash: string;
        timestamp: bigint;
        actionTaken: boolean;
        actionId: bigint;
      }
    ],
    "view"
  >;

  getAgentDecisions: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getDecision: TypedContractMethod<
    [decisionId: BigNumberish],
    [DecisionLogger.DecisionStructOutput],
    "view"
  >;

  getDecisionCount: TypedContractMethod<[], [bigint], "view">;

  getLatestRisk: TypedContractMethod<
    [user: AddressLike],
    [DecisionLogger.RiskSnapshotStructOutput],
    "view"
  >;

  getRecentDecisions: TypedContractMethod<
    [count: BigNumberish],
    [DecisionLogger.DecisionStructOutput[]],
    "view"
  >;

  getRiskHistory: TypedContractMethod<
    [user: AddressLike],
    [DecisionLogger.RiskSnapshotStructOutput[]],
    "view"
  >;

  getRiskHistoryCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalDecisions: bigint;
        _totalThreats: bigint;
        _totalProtections: bigint;
      }
    ],
    "view"
  >;

  getUserDecisions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  latestRiskSnapshot: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        timestamp: bigint;
        overallRisk: bigint;
        liquidationRisk: bigint;
        volatilityScore: bigint;
        protocolRisk: bigint;
        smartContractRisk: bigint;
        detailsHash: string;
      }
    ],
    "view"
  >;

  logDecision: TypedContractMethod<
    [
      agentId: BigNumberish,
      targetUser: AddressLike,
      decisionType: BigNumberish,
      riskLevel: BigNumberish,
      confidence: BigNumberish,
      analysisHash: BytesLike,
      dataHash: BytesLike,
      actionTaken: boolean,
      actionId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  riskHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        timestamp: bigint;
        overallRisk: bigint;
        liquidationRisk: bigint;
        volatilityScore: bigint;
        protocolRisk: bigint;
        smartContractRisk: bigint;
        detailsHash: string;
      }
    ],
    "view"
  >;

  setLoggerAuthorization: TypedContractMethod<
    [logger: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  totalProtectionsTriggered: TypedContractMethod<[], [bigint], "view">;

  totalThreatsDetected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRiskSnapshot: TypedContractMethod<
    [
      user: AddressLike,
      overallRisk: BigNumberish,
      liquidationRisk: BigNumberish,
      volatilityScore: BigNumberish,
      protocolRisk: BigNumberish,
      smartContractRisk: BigNumberish,
      detailsHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  userDecisions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentDecisions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizedLoggers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "decisions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        agentId: bigint;
        targetUser: string;
        decisionType: bigint;
        riskLevel: bigint;
        confidence: bigint;
        analysisHash: string;
        dataHash: string;
        timestamp: bigint;
        actionTaken: boolean;
        actionId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentDecisions"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDecision"
  ): TypedContractMethod<
    [decisionId: BigNumberish],
    [DecisionLogger.DecisionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecisionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestRisk"
  ): TypedContractMethod<
    [user: AddressLike],
    [DecisionLogger.RiskSnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentDecisions"
  ): TypedContractMethod<
    [count: BigNumberish],
    [DecisionLogger.DecisionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRiskHistory"
  ): TypedContractMethod<
    [user: AddressLike],
    [DecisionLogger.RiskSnapshotStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRiskHistoryCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalDecisions: bigint;
        _totalThreats: bigint;
        _totalProtections: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDecisions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "latestRiskSnapshot"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        timestamp: bigint;
        overallRisk: bigint;
        liquidationRisk: bigint;
        volatilityScore: bigint;
        protocolRisk: bigint;
        smartContractRisk: bigint;
        detailsHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "logDecision"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      targetUser: AddressLike,
      decisionType: BigNumberish,
      riskLevel: BigNumberish,
      confidence: BigNumberish,
      analysisHash: BytesLike,
      dataHash: BytesLike,
      actionTaken: boolean,
      actionId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        timestamp: bigint;
        overallRisk: bigint;
        liquidationRisk: bigint;
        volatilityScore: bigint;
        protocolRisk: bigint;
        smartContractRisk: bigint;
        detailsHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setLoggerAuthorization"
  ): TypedContractMethod<
    [logger: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalProtectionsTriggered"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalThreatsDetected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRiskSnapshot"
  ): TypedContractMethod<
    [
      user: AddressLike,
      overallRisk: BigNumberish,
      liquidationRisk: BigNumberish,
      volatilityScore: BigNumberish,
      protocolRisk: BigNumberish,
      smartContractRisk: BigNumberish,
      detailsHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userDecisions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "DecisionLogged"
  ): TypedContractEvent<
    DecisionLoggedEvent.InputTuple,
    DecisionLoggedEvent.OutputTuple,
    DecisionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "LoggerAuthorized"
  ): TypedContractEvent<
    LoggerAuthorizedEvent.InputTuple,
    LoggerAuthorizedEvent.OutputTuple,
    LoggerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RiskSnapshotUpdated"
  ): TypedContractEvent<
    RiskSnapshotUpdatedEvent.InputTuple,
    RiskSnapshotUpdatedEvent.OutputTuple,
    RiskSnapshotUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ThreatDetected"
  ): TypedContractEvent<
    ThreatDetectedEvent.InputTuple,
    ThreatDetectedEvent.OutputTuple,
    ThreatDetectedEvent.OutputObject
  >;

  filters: {
    "DecisionLogged(uint256,uint256,address,uint8,uint8,uint256,uint256)": TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;
    DecisionLogged: TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;

    "LoggerAuthorized(address,bool)": TypedContractEvent<
      LoggerAuthorizedEvent.InputTuple,
      LoggerAuthorizedEvent.OutputTuple,
      LoggerAuthorizedEvent.OutputObject
    >;
    LoggerAuthorized: TypedContractEvent<
      LoggerAuthorizedEvent.InputTuple,
      LoggerAuthorizedEvent.OutputTuple,
      LoggerAuthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RiskSnapshotUpdated(address,uint8,uint256)": TypedContractEvent<
      RiskSnapshotUpdatedEvent.InputTuple,
      RiskSnapshotUpdatedEvent.OutputTuple,
      RiskSnapshotUpdatedEvent.OutputObject
    >;
    RiskSnapshotUpdated: TypedContractEvent<
      RiskSnapshotUpdatedEvent.InputTuple,
      RiskSnapshotUpdatedEvent.OutputTuple,
      RiskSnapshotUpdatedEvent.OutputObject
    >;

    "ThreatDetected(uint256,uint256,address,uint8,bytes32)": TypedContractEvent<
      ThreatDetectedEvent.InputTuple,
      ThreatDetectedEvent.OutputTuple,
      ThreatDetectedEvent.OutputObject
    >;
    ThreatDetected: TypedContractEvent<
      ThreatDetectedEvent.InputTuple,
      ThreatDetectedEvent.OutputTuple,
      ThreatDetectedEvent.OutputObject
    >;
  };
}
